# Generated by Django 5.1.1 on 2024-10-24 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('spreadsheet', 'Spreadsheet'), ('text', 'Text'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='projectfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
