# Generated by Django 5.1.1 on 2024-10-24 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projectfile_file_type_projectfile_uploaded_at'),
    ]

    operations = [
    ]
