# Generated by Django 5.1.1 on 2024-10-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_todo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonial_imgs')),
                ('client_name', models.CharField(max_length=20)),
                ('client_occupation', models.CharField(max_length=45)),
                ('client_story', models.TextField()),
            ],
        ),
    ]
