# Generated by Django 5.1.1 on 2024-10-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20241024_1909'),
    ]

    operations = [
    ]
