# Generated by Django 5.1.1 on 2024-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=40),
        ),
    ]
